version: '3.4'

services:
  dsi202202:
    image: dsi202202
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 05-python/00-helloworld.py "]
    ports:
      - 5678:5678
